### ISSUE TITLE
Whitespace elimination

### ISSUE THREAD

**Issue by lukemelia** [ZebraFlesh/ember-cli-happy-splitter#1]
In your example template code you show comment syntax as a way to eliminate whitespace between elements. Have you tried using handlebars whitespace control syntax? (http://stackoverflow.com/questions/15953293/handlebars-whitespace-control)

**Comment by ZebraFlesh** [comment]
Actually I was unaware of the whitespace control syntax.  Thank you for enlightening me!  Do you know, is there a way to automatically include this in the component? It's not leaping out at me, but that may be my inexperience with views and components.

**Comment by lukemelia** [comment]
@ZebraFlesh sure thing. I recently learned about it myself. I don't know of a way to automatically include this behavior.
